"""empty message

Revision ID: 558534c061fc
Revises: 
Create Date: 2024-10-04 23:58:44.765899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558534c061fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('click_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('unique_visitor_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['short_url_id'], ['short_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click_data')
    op.drop_table('short_url')
    # ### end Alembic commands ###
